package de.phasenrauschen.bicyweather;

import android.annotation.SuppressLint;

import java.util.ArrayList;

public class Location {

    private ArrayList<CityItem> pcityList;


    @SuppressLint("SuspiciousIndentation")
    public ArrayList<CityItem> getLocationArray() {


        pcityList = new ArrayList<>();

               pcityList.add(new CityItem(   "AACHEN-ORSBACH      ",    "10505"));
               pcityList.add(new CityItem(   "ABBEVILLE           ",    "07005"));
               pcityList.add(new CityItem(   "ABERDARON           ",    "03405"));
               pcityList.add(new CityItem(   "ABERDEEN            ",    "03091"));
               pcityList.add(new CityItem(   "ABERPORTH           ",    "03502"));
               pcityList.add(new CityItem(   "ADANA               ",    "17350"));
               pcityList.add(new CityItem(   "AHAUS               ",    "10309"));
               pcityList.add(new CityItem(   "AIGEN/ENNS          ",    "11157"));
               pcityList.add(new CityItem(   "AJACCIO             ",    "07761"));
               pcityList.add(new CityItem(   "AKUREYRI            ",    "04063"));
               pcityList.add(new CityItem(   "ALBACETE/LOS LLANOS ",    "08280"));
               pcityList.add(new CityItem(   "ALBORG              ",    "06030"));
               pcityList.add(new CityItem(   "ALDERSBACH-KRIESTORF",    "P681"));
               pcityList.add(new CityItem(   "ALENCON             ",    "07139"));
               pcityList.add(new CityItem(   "ALESUND AIRP        ",    "01210"));
               pcityList.add(new CityItem(   "ALEXANDROUPOLI      ",    "16627"));
               pcityList.add(new CityItem(   "ALFELD              ",    "10442"));
               pcityList.add(new CityItem(   "ALFHAUSEN           ",    "E626"));
               pcityList.add(new CityItem(   "ALICANTE            ",    "08360"));
               pcityList.add(new CityItem(   "ALMERIA             ",    "08487"));
               pcityList.add(new CityItem(   "ALSFELD-EIFA        ",    "L464"));
               pcityList.add(new CityItem(   "ALTA LUFTHAVN       ",    "01049"));
               pcityList.add(new CityItem(   "ALTENSTADT          ",    "10954"));
               pcityList.add(new CityItem(   "ALTGERINGSWALDE     ",    "O510"));
               pcityList.add(new CityItem(   "ALTNAHARRA          ",    "03044"));
               pcityList.add(new CityItem(   "ALTOMUENSTER-MAISBRU",    "P629"));
               pcityList.add(new CityItem(   "ALZEY               ",    "K685"));
               pcityList.add(new CityItem(   "AMBERG-UNTERAMMERSR.",    "P354"));
               pcityList.add(new CityItem(   "AMERANG-PFAFFING    ",    "P874"));
               pcityList.add(new CityItem(   "AMSTERDAM           ",    "06240"));
               pcityList.add(new CityItem(   "ANDERNACH           ",    "10520"));
               pcityList.add(new CityItem(   "ANDRAVIDA           ",    "16682"));
               pcityList.add(new CityItem(   "ANGERMUENDE         ",    "10291"));
               pcityList.add(new CityItem(   "ANKARA              ",    "17128"));
               pcityList.add(new CityItem(   "ANKLAM              ",    "B488"));
               pcityList.add(new CityItem(   "ANTALYA             ",    "17300"));
               pcityList.add(new CityItem(   "ARAD                ",    "15200"));
               pcityList.add(new CityItem(   "ARCHANGELSK         ",    "22550"));
               pcityList.add(new CityItem(   "ARKONA              ",    "10091"));
               pcityList.add(new CityItem(   "ARNSBERG-NEHEIM     ",    "H572"));
               pcityList.add(new CityItem(   "ARNSTEIN-MUEDESHEIM ",    "P125"));
               pcityList.add(new CityItem(   "ARTERN              ",    "10460"));
               pcityList.add(new CityItem(   "ASTRAHAN            ",    "34880"));
               pcityList.add(new CityItem(   "ATHEN               ",    "16716"));
               pcityList.add(new CityItem(   "ATTENKAM            ",    "P804"));
               pcityList.add(new CityItem(   "AUE                 ",    "O863"));
               pcityList.add(new CityItem(   "AUGSBURG            ",    "10852"));
               pcityList.add(new CityItem(   "AZOREN              ",    "08505"));
               pcityList.add(new CityItem(   "B.MARIENBG.         ",    "10526"));
               pcityList.add(new CityItem(   "BACAU               ",    "15150"));
               pcityList.add(new CityItem(   "BAD BERGZABERN      ",    "K988"));
               pcityList.add(new CityItem(   "BAD BERLEBURG-STÜNZE",    "H795"));
               pcityList.add(new CityItem(   "BAD DUERKHEIM       ",    "K881"));
               pcityList.add(new CityItem(   "BAD HARZBURG        ",    "E897"));
               pcityList.add(new CityItem(   "BAD HERSFELD        ",    "10542"));
               pcityList.add(new CityItem(   "BAD KOENIGSHOFEN    ",    "P033"));
               pcityList.add(new CityItem(   "BAD KOHLGRUB        ",    "P942"));
               pcityList.add(new CityItem(   "BAD KREUZNACH       ",    "K568"));
               pcityList.add(new CityItem(   "BAD LIPPSPRINGE     ",    "10430"));
               pcityList.add(new CityItem(   "BAD LOBENSTEIN      ",    "M965"));
               pcityList.add(new CityItem(   "BAD MERGENTHEIM-NEUN",    "Q076"));
               pcityList.add(new CityItem(   "BAD MUSKAU          ",    "O025"));
               pcityList.add(new CityItem(   "BAD NAUHEIM         ",    "L635"));
               pcityList.add(new CityItem(   "BAD NEUENAHR-AHRWEIL",    "K038"));
               pcityList.add(new CityItem(   "BAD SALZUFLEN       ",    "10325"));
               pcityList.add(new CityItem(   "BADAJOZ/TALAVERA    ",    "08330"));
               pcityList.add(new CityItem(   "BADEN-BADEN-GEROLDSA",    "Q411"));
               pcityList.add(new CityItem(   "BALASHOV            ",    "34152"));
               pcityList.add(new CityItem(   "BALDERSCHWANG       ",    "P916"));
               pcityList.add(new CityItem(   "BALINGEN-BRONNHPTN. ",    "Q740"));
               pcityList.add(new CityItem(   "BAMBERG             ",    "10675"));
               pcityList.add(new CityItem(   "BANJA LUKA          ",    "14542"));
               pcityList.add(new CityItem(   "BARCELONA           ",    "08181"));
               pcityList.add(new CityItem(   "BARI                ",    "16270"));
               pcityList.add(new CityItem(   "BARSINGHAUSEN-HOHENB",    "E744"));
               pcityList.add(new CityItem(   "BARTH               ",    "10180"));
               pcityList.add(new CityItem(   "BARUTH              ",    "10376"));
               pcityList.add(new CityItem(   "BASEL-MLH.          ",    "07299"));
               pcityList.add(new CityItem(   "BASSUM              ",    "E438"));
               pcityList.add(new CityItem(   "BASTIA              ",    "07790"));
               pcityList.add(new CityItem(   "BECKUM-UNTERBERG    ",    "H361"));
               pcityList.add(new CityItem(   "BEDFORD             ",    "03560"));
               pcityList.add(new CityItem(   "BEERFELDEN          ",    "L988"));
               pcityList.add(new CityItem(   "BELFAST             ",    "03917"));
               pcityList.add(new CityItem(   "BELGRAD             ",    "13274"));
               pcityList.add(new CityItem(   "BELM                ",    "10312"));
               pcityList.add(new CityItem(   "BELMULLET           ",    "03976"));
               pcityList.add(new CityItem(   "BEOGRAD/SURCIN      ",    "13272"));
               pcityList.add(new CityItem(   "BERGE               ",    "F431"));
               pcityList.add(new CityItem(   "BERGEN              ",    "01311"));
               pcityList.add(new CityItem(   "BERGEN-HOHNE        ",    "10238"));
               pcityList.add(new CityItem(   "BERKA, BAD (FLUGPLAT",    "M439"));
               pcityList.add(new CityItem(   "BERLIN-BUCH         ",    "G002"));
               pcityList.add(new CityItem(   "BERLIN-DAHLEM       ",    "10381"));
               pcityList.add(new CityItem(   "BERLIN-KANISWALL    ",    "G006"));
               pcityList.add(new CityItem(   "BERLIN-MARZAHN      ",    "G005"));
               pcityList.add(new CityItem(   "BERLIN-SCHOENEFELD  ",    "10385"));
               pcityList.add(new CityItem(   "BERLIN-TEGEL        ",    "10382"));
               pcityList.add(new CityItem(   "BERLIN-TEMPELHOF    ",    "10384"));
               pcityList.add(new CityItem(   "BERNBURG/SAALE      ",    "N548"));
               pcityList.add(new CityItem(   "BERTSDORF-HOERNITZ  ",    "O598"));
               pcityList.add(new CityItem(   "BERUS               ",    "10704"));
               pcityList.add(new CityItem(   "BEVERN              ",    "E818"));
               pcityList.add(new CityItem(   "BIALYSTOK           ",    "12295"));
               pcityList.add(new CityItem(   "BIELEFELD-DEPPENDORF",    "H174"));
               pcityList.add(new CityItem(   "BIHAC               ",    "14528"));
               pcityList.add(new CityItem(   "BIRX                ",    "M805"));
               pcityList.add(new CityItem(   "BJELASNICA          ",    "14652"));
               pcityList.add(new CityItem(   "BJORNOYA            ",    "01028"));
               pcityList.add(new CityItem(   "BLANKENRATH         ",    "K463"));
               pcityList.add(new CityItem(   "BODOE               ",    "01152"));
               pcityList.add(new CityItem(   "BODRUM              ",    "17290"));
               pcityList.add(new CityItem(   "BOIZENBURG          ",    "10249"));
               pcityList.add(new CityItem(   "BOLTENHAGEN         ",    "10161"));
               pcityList.add(new CityItem(   "BOLU                ",    "17070"));
               pcityList.add(new CityItem(   "BORDEAUX            ",    "07510"));
               pcityList.add(new CityItem(   "BORKEN/WESTFALEN    ",    "H411"));
               pcityList.add(new CityItem(   "BORKUM-FLUGPLATZ    ",    "E008"));
               pcityList.add(new CityItem(   "BOTOSANI            ",    "15020"));
               pcityList.add(new CityItem(   "BOURGES             ",    "07255"));
               pcityList.add(new CityItem(   "BRATISLAVA          ",    "11816"));
               pcityList.add(new CityItem(   "BRAUNECK            ",    "Z929"));
               pcityList.add(new CityItem(   "BRAUNLAGE           ",    "10452"));
               pcityList.add(new CityItem(   "BRAUNSCHWG.         ",    "10348"));
               pcityList.add(new CityItem(   "BRECHERSPITZE       ",    "Z931"));
               pcityList.add(new CityItem(   "BREMEN              ",    "10224"));
               pcityList.add(new CityItem(   "BREMERHAVEN         ",    "10129"));
               pcityList.add(new CityItem(   "BREMERVOERDE        ",    "10139"));
               pcityList.add(new CityItem(   "BRESCIA/GHEDI       ",    "16088"));
               pcityList.add(new CityItem(   "BREST               ",    "07110"));
               pcityList.add(new CityItem(   "BREST               ",    "33008"));
               pcityList.add(new CityItem(   "BRIDLINGTON         ",    "03292"));
               pcityList.add(new CityItem(   "BRILON-THÜLEN       ",    "H591"));
               pcityList.add(new CityItem(   "BRINDISI            ",    "16320"));
               pcityList.add(new CityItem(   "BRISTOL/FILTON      ",    "03628"));
               pcityList.add(new CityItem(   "BROCKEN             ",    "10453"));
               pcityList.add(new CityItem(   "BRUENN              ",    "11723"));
               pcityList.add(new CityItem(   "BRUNNSTEINSPITZE    ",    "Z922"));
               pcityList.add(new CityItem(   "BUCHEN,KR.NECKAR-OD.",    "Q055"));
               pcityList.add(new CityItem(   "BUCHENBACH          ",    "Q811"));
               pcityList.add(new CityItem(   "BUCHENHOFEN         ",    "H547"));
               pcityList.add(new CityItem(   "BUDAPEST/LORINC     ",    "12843"));
               pcityList.add(new CityItem(   "BUECHEL             ",    "10613"));
               pcityList.add(new CityItem(   "BUECKEBURG          ",    "10335"));
               pcityList.add(new CityItem(   "BUKAREST/OTOPENI    ",    "15421"));
               pcityList.add(new CityItem(   "BURGAS              ",    "15655"));
               pcityList.add(new CityItem(   "BURGOS-VILLAFRIA    ",    "08075"));
               pcityList.add(new CityItem(   "BURGWALD-BOTTENDORF ",    "L217"));
               pcityList.add(new CityItem(   "BURSA               ",    "17116"));
               pcityList.add(new CityItem(   "CAEN                ",    "07027"));
               pcityList.add(new CityItem(   "CAMBORNE            ",    "03808"));
               pcityList.add(new CityItem(   "CAMPOBASSO          ",    "16252"));
               pcityList.add(new CityItem(   "CAPO BELLAVISTA     ",    "16550"));
               pcityList.add(new CityItem(   "CAPRI               ",    "16294"));
               pcityList.add(new CityItem(   "CARLISLE            ",    "03220"));
               pcityList.add(new CityItem(   "CARLSFELD           ",    "10574"));
               pcityList.add(new CityItem(   "CARSAMBA/SAMSUN     ",    "17031"));
               pcityList.add(new CityItem(   "CELLE               ",    "10343"));
               pcityList.add(new CityItem(   "CEREPOVEC           ",    "27113"));
               pcityList.add(new CityItem(   "CHARTERHALL         ",    "03158"));
               pcityList.add(new CityItem(   "CHEMNITZ            ",    "10577"));
               pcityList.add(new CityItem(   "CHIEMING            ",    "10982"));
               pcityList.add(new CityItem(   "CHOJNICE            ",    "12235"));
               pcityList.add(new CityItem(   "CHURANOV            ",    "11457"));
               pcityList.add(new CityItem(   "CLERMONT            ",    "07460"));
               pcityList.add(new CityItem(   "CLUJ-NAPOCA         ",    "15120"));
               pcityList.add(new CityItem(   "COBURG              ",    "10671"));
               pcityList.add(new CityItem(   "COELBE              ",    "L319"));
               pcityList.add(new CityItem(   "COIMBRA/CERVACHE    ",    "08548"));
               pcityList.add(new CityItem(   "CONSTANTA           ",    "15480"));
               pcityList.add(new CityItem(   "CORDOBA             ",    "08410"));
               pcityList.add(new CityItem(   "CORK AIRPORT        ",    "03955"));
               pcityList.add(new CityItem(   "COSCHEN             ",    "F695"));
               pcityList.add(new CityItem(   "COTTBUS             ",    "10496"));
               pcityList.add(new CityItem(   "CRANWELL            ",    "03379"));
               pcityList.add(new CityItem(   "CUXHAVEN            ",    "10131"));
               pcityList.add(new CityItem(   "DACHWIG             ",    "M348"));
               pcityList.add(new CityItem(   "DALATANGI           ",    "04097"));
               pcityList.add(new CityItem(   "DARMSTADT           ",    "L886"));
               pcityList.add(new CityItem(   "DEBRECEN            ",    "12882"));
               pcityList.add(new CityItem(   "DEMKER              ",    "N272"));
               pcityList.add(new CityItem(   "DEUSELBACH          ",    "10615"));
               pcityList.add(new CityItem(   "DEUTSCHNEUDORF-BRUED",    "O842"));
               pcityList.add(new CityItem(   "DIEPHOLZ            ",    "10321"));
               pcityList.add(new CityItem(   "DIJON               ",    "07280"));
               pcityList.add(new CityItem(   "DILLENBURG          ",    "L411"));
               pcityList.add(new CityItem(   "DILLINGEN-FRISTINGEN",    "P602"));
               pcityList.add(new CityItem(   "DIPPOLDISWALDE-REIN.",    "O660"));
               pcityList.add(new CityItem(   "DISHFORTH AIRFIELD  ",    "03261"));
               pcityList.add(new CityItem(   "DIYARBAKIR          ",    "17280"));
               pcityList.add(new CityItem(   "DNIPROPETROVSK      ",    "34504"));
               pcityList.add(new CityItem(   "DOBBIACO            ",    "16033"));
               pcityList.add(new CityItem(   "DOBERLUG-KIRCHHAIN  ",    "10490"));
               pcityList.add(new CityItem(   "DOERNICK            ",    "10150"));
               pcityList.add(new CityItem(   "DOERPEN             ",    "E402"));
               pcityList.add(new CityItem(   "DONAUWOERTH-OSTERWE.",    "P515"));
               pcityList.add(new CityItem(   "DONETSK             ",    "34519"));
               pcityList.add(new CityItem(   "DRESDEN             ",    "10488"));
               pcityList.add(new CityItem(   "DRESDEN-HOSTERWITZ  ",    "O458"));
               pcityList.add(new CityItem(   "DRESDEN-STREHLEN    ",    "O457"));
               pcityList.add(new CityItem(   "DREWITZ BEI BURG    ",    "N398"));
               pcityList.add(new CityItem(   "DUBLIN              ",    "03969"));
               pcityList.add(new CityItem(   "DUBROVNIK           ",    "14474"));
               pcityList.add(new CityItem(   "DUERRNBACHHORN      ",    "Z939"));
               pcityList.add(new CityItem(   "DUESSELDORF         ",    "10400"));
               pcityList.add(new CityItem(   "DUISBURG-BAERL      ",    "H419"));
               pcityList.add(new CityItem(   "EBERSBERG-HALBING   ",    "P768"));
               pcityList.add(new CityItem(   "EBRACH              ",    "P148"));
               pcityList.add(new CityItem(   "EDIRNE              ",    "17050"));
               pcityList.add(new CityItem(   "EGER                ",    "11406"));
               pcityList.add(new CityItem(   "EICHSTAETT-LANDERSH.",    "P522"));
               pcityList.add(new CityItem(   "EILAT               ",    "40199"));
               pcityList.add(new CityItem(   "EINDHOVEN           ",    "06370"));
               pcityList.add(new CityItem(   "EISENACH            ",    "10540"));
               pcityList.add(new CityItem(   "EISENSTADT          ",    "11190"));
               pcityList.add(new CityItem(   "EKATERINBURG        ",    "28440"));
               pcityList.add(new CityItem(   "ELBLAG              ",    "12160"));
               pcityList.add(new CityItem(   "ELLWANGEN-RINDELBACH",    "Q382"));
               pcityList.add(new CityItem(   "ELPERSBUETTEL       ",    "10130"));
               pcityList.add(new CityItem(   "ELSENDORF-HORNECK   ",    "P548"));
               pcityList.add(new CityItem(   "ELSTER, BAD-SOHL    ",    "O980"));
               pcityList.add(new CityItem(   "ELZACH-FISNACHT     ",    "Q712"));
               pcityList.add(new CityItem(   "EMDEN-FLUGPLATZ     ",    "10200"));
               pcityList.add(new CityItem(   "EMMENDINGEN-MUNDING.",    "Q702"));
               pcityList.add(new CityItem(   "EPPINGEN-ELSENZ     ",    "Q221"));
               pcityList.add(new CityItem(   "ERFDE               ",    "A351"));
               pcityList.add(new CityItem(   "ERFURT              ",    "10554"));
               pcityList.add(new CityItem(   "ERZURUM             ",    "17096"));
               pcityList.add(new CityItem(   "ESCHWEGE            ",    "L291"));
               pcityList.add(new CityItem(   "ESKDALEMUIR         ",    "03162"));
               pcityList.add(new CityItem(   "ESLOHE              ",    "H579"));
               pcityList.add(new CityItem(   "ESSEN               ",    "10410"));
               pcityList.add(new CityItem(   "EXETER APT          ",    "03839"));
               pcityList.add(new CityItem(   "FAGERNES            ",    "01368"));
               pcityList.add(new CityItem(   "FAHRENBERG          ",    "Z925"));
               pcityList.add(new CityItem(   "FALKENBERG,KR.ROTTAL",    "P674"));
               pcityList.add(new CityItem(   "FARO                ",    "08554"));
               pcityList.add(new CityItem(   "FASSBERG            ",    "10246"));
               pcityList.add(new CityItem(   "FELDBERG/MECKLENBURG",    "10282"));
               pcityList.add(new CityItem(   "FELDBERG/S.         ",    "10908"));
               pcityList.add(new CityItem(   "FELDKIRCH           ",    "11105"));
               pcityList.add(new CityItem(   "FELLHORN            ",    "Z905"));
               pcityList.add(new CityItem(   "FERRARA             ",    "16138"));
               pcityList.add(new CityItem(   "FEUCHTWANGEN        ",    "10756"));
               pcityList.add(new CityItem(   "FICHTELBERG         ",    "10578"));
               pcityList.add(new CityItem(   "FICHTELBERG/OBERFRA.",    "P182"));
               pcityList.add(new CityItem(   "FLENSBURG           ",    "10033"));
               pcityList.add(new CityItem(   "FLORES/AZOREN       ",    "08501"));
               pcityList.add(new CityItem(   "FOKSTUA 2           ",    "01238"));
               pcityList.add(new CityItem(   "FRANKFURT WESTEND   ",    "L841"));
               pcityList.add(new CityItem(   "FRANKFURT/M         ",    "10637"));
               pcityList.add(new CityItem(   "FREIBURG            ",    "10803"));
               pcityList.add(new CityItem(   "FREIBURG/ELBE       ",    "E082"));
               pcityList.add(new CityItem(   "FREUDENBERG/MAIN-BOX",    "Q062"));
               pcityList.add(new CityItem(   "FREUDENST.          ",    "10815"));
               pcityList.add(new CityItem(   "FREYSTADT-OBERNDORF ",    "P339"));
               pcityList.add(new CityItem(   "FRIEDRICHSHFN UNTER.",    "Q978"));
               pcityList.add(new CityItem(   "FRIESOYTHE-ALTENOYTH",    "10210"));
               pcityList.add(new CityItem(   "FRITZLAR            ",    "10439"));
               pcityList.add(new CityItem(   "FROSON              ",    "02226"));
               pcityList.add(new CityItem(   "FUERSTENZELL        ",    "10895"));
               pcityList.add(new CityItem(   "FULDA               ",    "L585"));
               pcityList.add(new CityItem(   "FUNCHAL             ",    "08521"));
               pcityList.add(new CityItem(   "FUNTENSEETAUERN     ",    "Z947"));
               pcityList.add(new CityItem(   "GARDELEGEN          ",    "10359"));
               pcityList.add(new CityItem(   "GARMISCH            ",    "10963"));
               pcityList.add(new CityItem(   "GARSEBACH BEI MEISSE",    "O348"));
               pcityList.add(new CityItem(   "GAZIANTEP           ",    "17260"));
               pcityList.add(new CityItem(   "GEILENKIRCHEN       ",    "10500"));
               pcityList.add(new CityItem(   "GEISENHEIM          ",    "10628"));
               pcityList.add(new CityItem(   "GEISINGEN           ",    "Q848"));
               pcityList.add(new CityItem(   "GELBELSEE           ",    "10777"));
               pcityList.add(new CityItem(   "GELDERN-WALBECK     ",    "H401"));
               pcityList.add(new CityItem(   "GENF                ",    "06700"));
               pcityList.add(new CityItem(   "GENTHIN             ",    "10365"));
               pcityList.add(new CityItem(   "GENUA               ",    "16120"));
               pcityList.add(new CityItem(   "GERA                ",    "10567"));
               pcityList.add(new CityItem(   "GERONA/COST.BRAVA   ",    "08184"));
               pcityList.add(new CityItem(   "GEVELSBERG-OBERB.   ",    "H542"));
               pcityList.add(new CityItem(   "GIESSEN             ",    "10532"));
               pcityList.add(new CityItem(   "GILSERBERG-MOISCHEID",    "L340"));
               pcityList.add(new CityItem(   "GOERLITZ            ",    "10499"));
               pcityList.add(new CityItem(   "GOETEBORG           ",    "02513"));
               pcityList.add(new CityItem(   "GOETTENDORF         ",    "M799"));
               pcityList.add(new CityItem(   "GOETTINGEN          ",    "10444"));
               pcityList.add(new CityItem(   "GOLDBERG            ",    "10168"));
               pcityList.add(new CityItem(   "GOLLHOFEN           ",    "P238"));
               pcityList.add(new CityItem(   "GOMEL               ",    "33041"));
               pcityList.add(new CityItem(   "GORZOW WLKP         ",    "12300"));
               pcityList.add(new CityItem(   "GOSPIC              ",    "14330"));
               pcityList.add(new CityItem(   "GOTTFRIEDING        ",    "10872"));
               pcityList.add(new CityItem(   "GR.ARBER            ",    "10791"));
               pcityList.add(new CityItem(   "GRADACAC            ",    "14554"));
               pcityList.add(new CityItem(   "GRAEFENBERG-KASBERG ",    "P265"));
               pcityList.add(new CityItem(   "GRAINERT-REHBERG    ",    "P594"));
               pcityList.add(new CityItem(   "GRAMBEK             ",    "A981"));
               pcityList.add(new CityItem(   "GRAMBOW-SCHWENNENZ  ",    "B898"));
               pcityList.add(new CityItem(   "GRANADA/AEROPUERTO  ",    "08419"));
               pcityList.add(new CityItem(   "GRAZ FL.            ",    "11240"));
               pcityList.add(new CityItem(   "GREIFSWALD          ",    "10184"));
               pcityList.add(new CityItem(   "GREIFSWALDER OIE    ",    "10097"));
               pcityList.add(new CityItem(   "GROSS LUESEWITZ     ",    "B334"));
               pcityList.add(new CityItem(   "GROSSENKNETEN-AHL.  ",    "E426"));
               pcityList.add(new CityItem(   "GROSSENLACH MANNENW.",    "Q351"));
               pcityList.add(new CityItem(   "GROSSETO            ",    "16206"));
               pcityList.add(new CityItem(   "GRUENDAU-BREITENBORN",    "L771"));
               pcityList.add(new CityItem(   "GRUENOW             ",    "10289"));
               pcityList.add(new CityItem(   "GUENZBURG           ",    "P606"));
               pcityList.add(new CityItem(   "GUERNSEY            ",    "03894"));
               pcityList.add(new CityItem(   "GYOR                ",    "12822"));
               pcityList.add(new CityItem(   "HAHN                ",    "10616"));
               pcityList.add(new CityItem(   "HAIFA               ",    "40155"));
               pcityList.add(new CityItem(   "HAMAR-STAVSBERG     ",    "01385"));
               pcityList.add(new CityItem(   "HAMBURG-FU.         ",    "10147"));
               pcityList.add(new CityItem(   "HAMBURG-NEUWIEDENTH.",    "C720"));
               pcityList.add(new CityItem(   "HAMELN-HASTENBECK   ",    "E739"));
               pcityList.add(new CityItem(   "HAMMERFEST          ",    "01052"));
               pcityList.add(new CityItem(   "HANKO               ",    "02982"));
               pcityList.add(new CityItem(   "HANNOVER            ",    "10338"));
               pcityList.add(new CityItem(   "HARBURG             ",    "10850"));
               pcityList.add(new CityItem(   "HARSTAD             ",    "01180"));
               pcityList.add(new CityItem(   "HARZGERODE          ",    "10458"));
               pcityList.add(new CityItem(   "HATTSTEDT           ",    "A226"));
               pcityList.add(new CityItem(   "HAWARDEN            ",    "03321"));
               pcityList.add(new CityItem(   "HECHINGEN           ",    "Q651"));
               pcityList.add(new CityItem(   "HECKELBERG          ",    "F361"));
               pcityList.add(new CityItem(   "HEINERSREUTH-VOLLHOF",    "P175"));
               pcityList.add(new CityItem(   "HEINSBERG-SCHLEIDEN ",    "H606"));
               pcityList.add(new CityItem(   "HELGOLAND           ",    "10015"));
               pcityList.add(new CityItem(   "HELMSTEDT           ",    "E798"));
               pcityList.add(new CityItem(   "HELSINKI/VANTAA     ",    "02974"));
               pcityList.add(new CityItem(   "HERAKLION           ",    "16754"));
               pcityList.add(new CityItem(   "HERMARINGEN-ALLEWIND",    "Q485"));
               pcityList.add(new CityItem(   "HERZBERG            ",    "E944"));
               pcityList.add(new CityItem(   "HERZOGSTANDBAHN     ",    "Z926"));
               pcityList.add(new CityItem(   "HIDDENSEE-VITTE     ",    "B006"));
               pcityList.add(new CityItem(   "HILGENROTH          ",    "K017"));
               pcityList.add(new CityItem(   "HOCHGRATBAHN        ",    "Z902"));
               pcityList.add(new CityItem(   "HOELLGRABEN         ",    "Z948"));
               pcityList.add(new CityItem(   "HOERMOOS            ",    "Z901"));
               pcityList.add(new CityItem(   "HOF                 ",    "10685"));
               pcityList.add(new CityItem(   "HOHENPEISS.BG       ",    "10962"));
               pcityList.add(new CityItem(   "HOHERODSKOPF (VOGELS",    "10534"));
               pcityList.add(new CityItem(   "HOHN                ",    "10038"));
               pcityList.add(new CityItem(   "HOHWACHT            ",    "A481"));
               pcityList.add(new CityItem(   "HOLESOV             ",    "11774"));
               pcityList.add(new CityItem(   "HOLZDORF            ",    "10476"));
               pcityList.add(new CityItem(   "HOLZKIRCHEN         ",    "P856"));
               pcityList.add(new CityItem(   "HOYERSWERDA         ",    "10495"));
               pcityList.add(new CityItem(   "HUEMMERICH          ",    "K057"));
               pcityList.add(new CityItem(   "IBIZA               ",    "08373"));
               pcityList.add(new CityItem(   "IDAR-OBERSTEIN      ",    "10618"));
               pcityList.add(new CityItem(   "INEBOLU             ",    "17024"));
               pcityList.add(new CityItem(   "INGELFINGEN-STACHEN.",    "Q165"));
               pcityList.add(new CityItem(   "INGOLSTADT          ",    "10860"));
               pcityList.add(new CityItem(   "INNSBRUCK FL.       ",    "11120"));
               pcityList.add(new CityItem(   "ISLE OF MAN/ROUAL.  ",    "03204"));
               pcityList.add(new CityItem(   "ISTANBUL            ",    "17060"));
               pcityList.add(new CityItem(   "ITZEHOE             ",    "10142"));
               pcityList.add(new CityItem(   "IVALO               ",    "02807"));
               pcityList.add(new CityItem(   "IVAN SEDLO          ",    "14650"));
               pcityList.add(new CityItem(   "IVANO-FRANKIVSK     ",    "33526"));
               pcityList.add(new CityItem(   "IZMIR/ADNAN MENDERE ",    "17219"));
               pcityList.add(new CityItem(   "JAJCE               ",    "14543"));
               pcityList.add(new CityItem(   "JENA (STERNWARTE)   ",    "M552"));
               pcityList.add(new CityItem(   "JENNER              ",    "Z949"));
               pcityList.add(new CityItem(   "JEREZ DE LA FRONTERA",    "08451"));
               pcityList.add(new CityItem(   "JERSEY-AIRPORT      ",    "03895"));
               pcityList.add(new CityItem(   "JERUSALEM           ",    "40184"));
               pcityList.add(new CityItem(   "JESSNITZ            ",    "N566"));
               pcityList.add(new CityItem(   "JONKOPING           ",    "02550"));
               pcityList.add(new CityItem(   "K.ASTEN             ",    "10427"));
               pcityList.add(new CityItem(   "KAHL (MAIN)         ",    "P100"));
               pcityList.add(new CityItem(   "KAISERSBACH-CRONHUET",    "10747"));
               pcityList.add(new CityItem(   "KAISERSLAUTERN      ",    "K863"));
               pcityList.add(new CityItem(   "KAJAANI             ",    "02897"));
               pcityList.add(new CityItem(   "KALISZ              ",    "12435"));
               pcityList.add(new CityItem(   "KALL-SISTIG         ",    "H981"));
               pcityList.add(new CityItem(   "KAMPENWAND          ",    "Z937"));
               pcityList.add(new CityItem(   "KANZELWAND          ",    "Z904"));
               pcityList.add(new CityItem(   "KARLSHAGEN          ",    "B382"));
               pcityList.add(new CityItem(   "KARLSTAD            ",    "02418"));
               pcityList.add(new CityItem(   "KARUP               ",    "06060"));
               pcityList.add(new CityItem(   "KAUFBEUREN          ",    "P817"));
               pcityList.add(new CityItem(   "KAUNAS POCIUNAI     ",    "26629"));
               pcityList.add(new CityItem(   "KAYSERI/ERKILET     ",    "17195"));
               pcityList.add(new CityItem(   "KAZAN               ",    "27595"));
               pcityList.add(new CityItem(   "KEMPTEN             ",    "10946"));
               pcityList.add(new CityItem(   "KENLEY              ",    "03781"));
               pcityList.add(new CityItem(   "KIEFERSFELDEN       ",    "P975"));
               pcityList.add(new CityItem(   "KIEL-H.             ",    "10046"));
               pcityList.add(new CityItem(   "KIELCE              ",    "12570"));
               pcityList.add(new CityItem(   "KIEW                ",    "33345"));
               pcityList.add(new CityItem(   "KINLOSS             ",    "03066"));
               pcityList.add(new CityItem(   "KIRCHBERG-JAGST     ",    "Q292"));
               pcityList.add(new CityItem(   "KIRCHDORF/POEL      ",    "B308"));
               pcityList.add(new CityItem(   "KIRKENES            ",    "01089"));
               pcityList.add(new CityItem(   "KIRKWALL            ",    "03017"));
               pcityList.add(new CityItem(   "KISSINGEN           ",    "10658"));
               pcityList.add(new CityItem(   "KITZINGEN           ",    "P232"));
               pcityList.add(new CityItem(   "KL.FELDBG./TS.      ",    "10635"));
               pcityList.add(new CityItem(   "KLAGENFURT FL.      ",    "11231"));
               pcityList.add(new CityItem(   "KLAIPEDA            ",    "26509"));
               pcityList.add(new CityItem(   "KLEINER INSELBERG   ",    "M620"));
               pcityList.add(new CityItem(   "KLETTWITZ           ",    "F951"));
               pcityList.add(new CityItem(   "KLEVE               ",    "H203"));
               pcityList.add(new CityItem(   "KLIPPENECK          ",    "10818"));
               pcityList.add(new CityItem(   "KLITSCHEN BEI TORGAU",    "O057"));
               pcityList.add(new CityItem(   "KNIN                ",    "14442"));
               pcityList.add(new CityItem(   "KOCELOVICE          ",    "11487"));
               pcityList.add(new CityItem(   "KOELN-STAMMHEIM     ",    "H744"));
               pcityList.add(new CityItem(   "KOELN/BONN          ",    "10513"));
               pcityList.add(new CityItem(   "KOENIGSBERG         ",    "26702"));
               pcityList.add(new CityItem(   "KOESCHING           ",    "P532"));
               pcityList.add(new CityItem(   "KOETHEN (ANHALT)    ",    "N652"));
               pcityList.add(new CityItem(   "KOJNAS              ",    "22583"));
               pcityList.add(new CityItem(   "KONOTOP             ",    "33261"));
               pcityList.add(new CityItem(   "KONSTANZ            ",    "10929"));
               pcityList.add(new CityItem(   "KONYA               ",    "17244"));
               pcityList.add(new CityItem(   "KOOY                ",    "06235"));
               pcityList.add(new CityItem(   "KOPAONIK            ",    "13378"));
               pcityList.add(new CityItem(   "KOPENHAGEN          ",    "06180"));
               pcityList.add(new CityItem(   "KORFU               ",    "16641"));
               pcityList.add(new CityItem(   "KOSICE              ",    "11968"));
               pcityList.add(new CityItem(   "KOSZALIN            ",    "12105"));
               pcityList.add(new CityItem(   "KRAGUJEVAC          ",    "13278"));
               pcityList.add(new CityItem(   "KRAKOW              ",    "12566"));
               pcityList.add(new CityItem(   "KRALJEVO            ",    "13376"));
               pcityList.add(new CityItem(   "KRANZBERG           ",    "Z919"));
               pcityList.add(new CityItem(   "KREIPITZSCH         ",    "N924"));
               pcityList.add(new CityItem(   "KRISTIANSAND        ",    "01452"));
               pcityList.add(new CityItem(   "KRISTIANSUND        ",    "01223"));
               pcityList.add(new CityItem(   "KRONACH             ",    "P066"));
               pcityList.add(new CityItem(   "KRYVYI RIH          ",    "33791"));
               pcityList.add(new CityItem(   "KUBSCHUETZ,KR.BAUTZ.",    "O384"));
               pcityList.add(new CityItem(   "KUEHROINT           ",    "Z946"));
               pcityList.add(new CityItem(   "KUEMMERSBRUCK       ",    "10771"));
               pcityList.add(new CityItem(   "KUGGOEREN AMOS      ",    "02355"));
               pcityList.add(new CityItem(   "KUKES               ",    "13610"));
               pcityList.add(new CityItem(   "KUOPIO              ",    "02917"));
               pcityList.add(new CityItem(   "KYRITZ              ",    "10267"));
               pcityList.add(new CityItem(   "KYTHIRA             ",    "16743"));
               pcityList.add(new CityItem(   "LA CORUNA           ",    "08001"));
               pcityList.add(new CityItem(   "LA HAGUE            ",    "07020"));
               pcityList.add(new CityItem(   "LAAGE               ",    "10172"));
               pcityList.add(new CityItem(   "LAHR                ",    "10805"));
               pcityList.add(new CityItem(   "LAHTI               ",    "02965"));
               pcityList.add(new CityItem(   "LAJES/AZOREN        ",    "08509"));
               pcityList.add(new CityItem(   "LANDSHUT-REITHOF    ",    "P655"));
               pcityList.add(new CityItem(   "LANGENLIPSDORF      ",    "F707"));
               pcityList.add(new CityItem(   "LANZAROTE           ",    "60040"));
               pcityList.add(new CityItem(   "LARISSA             ",    "16648"));
               pcityList.add(new CityItem(   "LARKHILL            ",    "03743"));
               pcityList.add(new CityItem(   "LARNAKA             ",    "17609"));
               pcityList.add(new CityItem(   "LAS PALMAS          ",    "60030"));
               pcityList.add(new CityItem(   "LAUCHSTAEDT, BAD    ",    "N769"));
               pcityList.add(new CityItem(   "LAUPHEIM            ",    "10837"));
               pcityList.add(new CityItem(   "LECHFELD            ",    "10856"));
               pcityList.add(new CityItem(   "LECK                ",    "10022"));
               pcityList.add(new CityItem(   "LEEMING             ",    "03257"));
               pcityList.add(new CityItem(   "LEEUWARDEN          ",    "06270"));
               pcityList.add(new CityItem(   "LEINEFELDE          ",    "10449"));
               pcityList.add(new CityItem(   "LEIPZIG             ",    "10471"));
               pcityList.add(new CityItem(   "LEIPZIG/SCHKEUDITZ  ",    "10469"));
               pcityList.add(new CityItem(   "LENNESTADT-THETEN   ",    "H678"));
               pcityList.add(new CityItem(   "LENZEN/ELBE         ",    "F105"));
               pcityList.add(new CityItem(   "LENZKIRCH-RUHBUEHL  ",    "Q823"));
               pcityList.add(new CityItem(   "LEON                ",    "08055"));
               pcityList.add(new CityItem(   "LERIDA              ",    "08171"));
               pcityList.add(new CityItem(   "LERWICK             ",    "03005"));
               pcityList.add(new CityItem(   "LESKOVAC            ",    "13389"));
               pcityList.add(new CityItem(   "LEUCHARS            ",    "03171"));
               pcityList.add(new CityItem(   "LEUCHTTURM A. WESER ",    "10124"));
               pcityList.add(new CityItem(   "LEUCHTTURM KIEL     ",    "10044"));
               pcityList.add(new CityItem(   "LEUTKIRCH-HERLAZHFN.",    "10945"));
               pcityList.add(new CityItem(   "LIBEREC             ",    "11603"));
               pcityList.add(new CityItem(   "LICHTENHAIN         ",    "10591"));
               pcityList.add(new CityItem(   "LICHTENTANNE        ",    "O805"));
               pcityList.add(new CityItem(   "LIEBENBURG-OTHFRESEN",    "E871"));
               pcityList.add(new CityItem(   "LIEPAJA             ",    "26406"));
               pcityList.add(new CityItem(   "LILLE               ",    "07015"));
               pcityList.add(new CityItem(   "LIMNOS              ",    "16650"));
               pcityList.add(new CityItem(   "LIMOGES             ",    "07434"));
               pcityList.add(new CityItem(   "LINDENBERG          ",    "10393"));
               pcityList.add(new CityItem(   "LINDERSPITZE        ",    "Z924"));
               pcityList.add(new CityItem(   "LINDERSPITZE-RINNE  ",    "Z923"));
               pcityList.add(new CityItem(   "LINKOPING           ",    "02562"));
               pcityList.add(new CityItem(   "LINZ FL.            ",    "11010"));
               pcityList.add(new CityItem(   "LIPPSTADT-BOEKENFOER",    "H377"));
               pcityList.add(new CityItem(   "LISBOA/GAGO COUTINHO",    "08579"));
               pcityList.add(new CityItem(   "LIST/SYLT           ",    "10020"));
               pcityList.add(new CityItem(   "LJUBLJANA/BRNIK     ",    "14014"));
               pcityList.add(new CityItem(   "LODZ                ",    "12465"));
               pcityList.add(new CityItem(   "LOEHNBERG-OBERSH.   ",    "L511"));
               pcityList.add(new CityItem(   "LOHR/MAIN-HALSBACH  ",    "P113"));
               pcityList.add(new CityItem(   "LONDON              ",    "03772"));
               pcityList.add(new CityItem(   "LOSSIEMOUTH         ",    "03068"));
               pcityList.add(new CityItem(   "LOZNICA             ",    "13262"));
               pcityList.add(new CityItem(   "LUBLIN RADAWIEC     ",    "12495"));
               pcityList.add(new CityItem(   "LUEBBEN-BLUMENFELDE ",    "F742"));
               pcityList.add(new CityItem(   "LUEBECK             ",    "10156"));
               pcityList.add(new CityItem(   "LUECHOW             ",    "10253"));
               pcityList.add(new CityItem(   "LUEDENSCHEID        ",    "10418"));
               pcityList.add(new CityItem(   "LUEDGE              ",    "10433"));
               pcityList.add(new CityItem(   "LUEDINGHAUSEN-BROCH.",    "H247"));
               pcityList.add(new CityItem(   "LULEA               ",    "02186"));
               pcityList.add(new CityItem(   "LUXEMBURG           ",    "06590"));
               pcityList.add(new CityItem(   "LYNEHAM             ",    "03740"));
               pcityList.add(new CityItem(   "LYON/SATOLAS        ",    "07481"));
               pcityList.add(new CityItem(   "MAASTRICHT          ",    "06380"));
               pcityList.add(new CityItem(   "MADRID/BARAJAS      ",    "08221"));
               pcityList.add(new CityItem(   "MAGDEBURG           ",    "10361"));
               pcityList.add(new CityItem(   "MAILAND             ",    "16080"));
               pcityList.add(new CityItem(   "MAINZ (ZDF)         ",    "K584"));
               pcityList.add(new CityItem(   "MAISACH-GALGEN      ",    "P741"));
               pcityList.add(new CityItem(   "MALAGA              ",    "08482"));
               pcityList.add(new CityItem(   "MALIN HEAD          ",    "03980"));
               pcityList.add(new CityItem(   "MALLERSDORF-PFB     ",    "P555"));
               pcityList.add(new CityItem(   "MALMO               ",    "02635"));
               pcityList.add(new CityItem(   "MALTA               ",    "16597"));
               pcityList.add(new CityItem(   "MANDERSCHEID        ",    "K440"));
               pcityList.add(new CityItem(   "MANNHEIM            ",    "10729"));
               pcityList.add(new CityItem(   "MANSCHNOW           ",    "10396"));
               pcityList.add(new CityItem(   "MANSTON             ",    "03797"));
               pcityList.add(new CityItem(   "MARCHKLAMM          ",    "Z921"));
               pcityList.add(new CityItem(   "MARCHKLAMM TAL      ",    "Z920"));
               pcityList.add(new CityItem(   "MARHAM              ",    "03482"));
               pcityList.add(new CityItem(   "MARIBOR/SLIVNICA    ",    "14026"));
               pcityList.add(new CityItem(   "MARIENBERG          ",    "10579"));
               pcityList.add(new CityItem(   "MARINA DI GINOSA    ",    "16325"));
               pcityList.add(new CityItem(   "MARKT ERLBACH-MOSBA.",    "P542"));
               pcityList.add(new CityItem(   "MARNITZ             ",    "10264"));
               pcityList.add(new CityItem(   "MARSEILLE           ",    "07650"));
               pcityList.add(new CityItem(   "MARTINRODA          ",    "M732"));
               pcityList.add(new CityItem(   "MEHRINGEN/ASL       ",    "N632"));
               pcityList.add(new CityItem(   "MEINERZHAGEN-REDLEND",    "H658"));
               pcityList.add(new CityItem(   "MEININGEN           ",    "10548"));
               pcityList.add(new CityItem(   "MELILLA             ",    "60338"));
               pcityList.add(new CityItem(   "MEMMINGEN           ",    "P801"));
               pcityList.add(new CityItem(   "MENORCA             ",    "08314"));
               pcityList.add(new CityItem(   "MENZ                ",    "F151"));
               pcityList.add(new CityItem(   "MERKLINGEN          ",    "Q579"));
               pcityList.add(new CityItem(   "MESSINA             ",    "16420"));
               pcityList.add(new CityItem(   "MESSSTETTEN         ",    "10827"));
               pcityList.add(new CityItem(   "METTEN              ",    "P572"));
               pcityList.add(new CityItem(   "METZINGEN           ",    "Q561"));
               pcityList.add(new CityItem(   "MICHELSTADT         ",    "L947"));
               pcityList.add(new CityItem(   "MICHELSTADT-V.      ",    "10648"));
               pcityList.add(new CityItem(   "MIKOLAJKI           ",    "12280"));
               pcityList.add(new CityItem(   "MILFORD HAVEN       ",    "03604"));
               pcityList.add(new CityItem(   "MILLAU              ",    "07558"));
               pcityList.add(new CityItem(   "MINSK               ",    "26850"));
               pcityList.add(new CityItem(   "MISKOLC             ",    "12772"));
               pcityList.add(new CityItem(   "MITTELNKIRCHEN-HOHEN",    "E099"));
               pcityList.add(new CityItem(   "MLAWA               ",    "12270"));
               pcityList.add(new CityItem(   "MOEHRENDORF-KLSEE.  ",    "P257"));
               pcityList.add(new CityItem(   "MOENCHENGLADBACH-HIL",    "H768"));
               pcityList.add(new CityItem(   "MOESLARNALM         ",    "Z936"));
               pcityList.add(new CityItem(   "MONTABAUR           ",    "K282"));
               pcityList.add(new CityItem(   "MONTE REAL          ",    "08540"));
               pcityList.add(new CityItem(   "MONTE TERMINILLO    ",    "16219"));
               pcityList.add(new CityItem(   "MONTELIMAR          ",    "07577"));
               pcityList.add(new CityItem(   "MONTPELLIER         ",    "07643"));
               pcityList.add(new CityItem(   "MOORGRUND-GRAEFENDOR",    "M405"));
               pcityList.add(new CityItem(   "MORINGEN-LUTTERBECK ",    "E839"));
               pcityList.add(new CityItem(   "MOSCOW/SHEREMETYEVO ",    "27613"));
               pcityList.add(new CityItem(   "MOSKAU              ",    "27612"));
               pcityList.add(new CityItem(   "MOSTAR              ",    "14648"));
               pcityList.add(new CityItem(   "MUEHLACKER          ",    "10736"));
               pcityList.add(new CityItem(   "MUEHLDORF           ",    "10875"));
               pcityList.add(new CityItem(   "MUELLHEIM           ",    "Q887"));
               pcityList.add(new CityItem(   "MUENCHEBERG         ",    "F475"));
               pcityList.add(new CityItem(   "MUENCHEN STADT      ",    "10865"));
               pcityList.add(new CityItem(   "MUENCHEN-FL.        ",    "10870"));
               pcityList.add(new CityItem(   "MUENSTER/OSNABR.    ",    "10315"));
               pcityList.add(new CityItem(   "MUGLA/DALAMAN       ",    "17295"));
               pcityList.add(new CityItem(   "MURCIA              ",    "08430"));
               pcityList.add(new CityItem(   "MURMANSK            ",    "22113"));
               pcityList.add(new CityItem(   "MYTILINI/AIRPORT    ",    "16667"));
               pcityList.add(new CityItem(   "Mittenwald-B.wiesen ",    "P948"));
               pcityList.add(new CityItem(   "MÜHLHAUSEN-GÖRMAR   ",    "M225"));
               pcityList.add(new CityItem(   "MÜNSINGEN-APFELSTETT",    "Q671"));
               pcityList.add(new CityItem(   "NAGYKANIZSA         ",    "12925"));
               pcityList.add(new CityItem(   "NANCY               ",    "07180"));
               pcityList.add(new CityItem(   "NANTES              ",    "07222"));
               pcityList.add(new CityItem(   "NAXOS               ",    "16732"));
               pcityList.add(new CityItem(   "NEBELHORN           ",    "Z907"));
               pcityList.add(new CityItem(   "NEBELHORN-KOBLAT    ",    "Z908"));
               pcityList.add(new CityItem(   "NEGOTIN             ",    "13295"));
               pcityList.add(new CityItem(   "NEU-ULRICHSTEIN     ",    "10537"));
               pcityList.add(new CityItem(   "NEUBULACH-OBERHAUGST",    "Q437"));
               pcityList.add(new CityItem(   "NEUBURG/DONAU       ",    "10853"));
               pcityList.add(new CityItem(   "NEUBURG/KAMMEL-LANGE",    "P308"));
               pcityList.add(new CityItem(   "NEUHAUS A.R.        ",    "10557"));
               pcityList.add(new CityItem(   "NEUHUETTEN/SPESSART ",    "10646"));
               pcityList.add(new CityItem(   "NEUKIRCHEN-HAUPTSCHW",    "L355"));
               pcityList.add(new CityItem(   "NEUNKIRCHEN-SEELSCHE",    "H862"));
               pcityList.add(new CityItem(   "NEUNKIRCHEN-WELLESW.",    "J815"));
               pcityList.add(new CityItem(   "NEURUPPIN-ALT RUPPIN",    "10271"));
               pcityList.add(new CityItem(   "NEUSTADT AM KULM    ",    "P280"));
               pcityList.add(new CityItem(   "NICOSIA             ",    "17610"));
               pcityList.add(new CityItem(   "NIDEGGEN-SCHMIDT    ",    "H827"));
               pcityList.add(new CityItem(   "NIEDERSTETTEN       ",    "10743"));
               pcityList.add(new CityItem(   "NIENBURG            ",    "E652"));
               pcityList.add(new CityItem(   "NIS                 ",    "13388"));
               pcityList.add(new CityItem(   "NIZZA               ",    "07690"));
               pcityList.add(new CityItem(   "NOERVENICH          ",    "10502"));
               pcityList.add(new CityItem(   "NORDERNEY           ",    "10113"));
               pcityList.add(new CityItem(   "NORDHOLZ            ",    "10136"));
               pcityList.add(new CityItem(   "NORDKOSTER          ",    "02500"));
               pcityList.add(new CityItem(   "NOSSEN              ",    "O536"));
               pcityList.add(new CityItem(   "NOTTINGHAM/MET      ",    "03354"));
               pcityList.add(new CityItem(   "NOTZINGEN           ",    "Q061"));
               pcityList.add(new CityItem(   "NOVI SAD            ",    "13168"));
               pcityList.add(new CityItem(   "NUERBURG-BARWEILER  ",    "10506"));
               pcityList.add(new CityItem(   "NUERNBERG           ",    "10763"));
               pcityList.add(new CityItem(   "NUERNBERG-NETZSTALL ",    "P333"));
               pcityList.add(new CityItem(   "OBERHACHING-LAUFZORN",    "P830"));
               pcityList.add(new CityItem(   "OBERHARZ AM BROCKEN ",    "N616"));
               pcityList.add(new CityItem(   "OBERSTDORF          ",    "10948"));
               pcityList.add(new CityItem(   "OBERSULM-WILLSBACH  ",    "Q242"));
               pcityList.add(new CityItem(   "OBERVIECHTACH       ",    "P372"));
               pcityList.add(new CityItem(   "ODENSE              ",    "06120"));
               pcityList.add(new CityItem(   "ODESSA              ",    "33837"));
               pcityList.add(new CityItem(   "OEHRINGEN           ",    "10742"));
               pcityList.add(new CityItem(   "OFFENBACH-WETTERPARK",    "10641"));
               pcityList.add(new CityItem(   "OHLSBACH            ",    "Q518"));
               pcityList.add(new CityItem(   "OLBERSLEBEN         ",    "M299"));
               pcityList.add(new CityItem(   "OLBIA/COSTA SMERALDA",    "16531"));
               pcityList.add(new CityItem(   "OLPENITZ            ",    "10042"));
               pcityList.add(new CityItem(   "OLSDORF             ",    "K419"));
               pcityList.add(new CityItem(   "OOSTENDE            ",    "06407"));
               pcityList.add(new CityItem(   "OPOLE               ",    "12530"));
               pcityList.add(new CityItem(   "ORLAND              ",    "01241"));
               pcityList.add(new CityItem(   "OSCHATZ             ",    "10480"));
               pcityList.add(new CityItem(   "OSIJEK-CEPIN        ",    "14280"));
               pcityList.add(new CityItem(   "OSLO-BLINDERN       ",    "01492"));
               pcityList.add(new CityItem(   "OSLO/GARDERMOEN     ",    "01384"));
               pcityList.add(new CityItem(   "OSTENFELD (RENDSBURG",    "A443"));
               pcityList.add(new CityItem(   "OSTERFELD           ",    "10565"));
               pcityList.add(new CityItem(   "OSTERFELDER         ",    "Z917"));
               pcityList.add(new CityItem(   "OSTHEIM V.D. RHOEN  ",    "P022"));
               pcityList.add(new CityItem(   "OSTRAVA/MOSNOV      ",    "11782"));
               pcityList.add(new CityItem(   "OVIEDO              ",    "08015"));
               pcityList.add(new CityItem(   "OY-MITTELBERG-PETERS",    "P924"));
               pcityList.add(new CityItem(   "PABSTORF            ",    "N520"));
               pcityList.add(new CityItem(   "PADENSTEDT (PONY-PAR",    "A653"));
               pcityList.add(new CityItem(   "PAGANELLA           ",    "16022"));
               pcityList.add(new CityItem(   "PALMA               ",    "08306"));
               pcityList.add(new CityItem(   "PAPHOS AIRPORT      ",    "17600"));
               pcityList.add(new CityItem(   "PARIS               ",    "07149"));
               pcityList.add(new CityItem(   "PAROS               ",    "16741"));
               pcityList.add(new CityItem(   "PARSBERG/OBERPFALZ  ",    "P441"));
               pcityList.add(new CityItem(   "PASSO ROLLE         ",    "16021"));
               pcityList.add(new CityItem(   "PAYERNE             ",    "06610"));
               pcityList.add(new CityItem(   "PEC                 ",    "13473"));
               pcityList.add(new CityItem(   "PECS/POGANY         ",    "12942"));
               pcityList.add(new CityItem(   "PELZERHAKEN         ",    "10152"));
               pcityList.add(new CityItem(   "PERL-NENNIG         ",    "J702"));
               pcityList.add(new CityItem(   "PERPIGNAN           ",    "07747"));
               pcityList.add(new CityItem(   "PESCARA             ",    "16230"));
               pcityList.add(new CityItem(   "PETROSK             ",    "22820"));
               pcityList.add(new CityItem(   "PFORZHEIM-ISPRINGEN ",    "Q332"));
               pcityList.add(new CityItem(   "PFULLENDORF         ",    "Q864"));
               pcityList.add(new CityItem(   "PIACENZA            ",    "16084"));
               pcityList.add(new CityItem(   "PIDING              ",    "P991"));
               pcityList.add(new CityItem(   "PIESTANY            ",    "11826"));
               pcityList.add(new CityItem(   "PIRMASENS           ",    "K925"));
               pcityList.add(new CityItem(   "PISA-S.GIUSTO       ",    "16158"));
               pcityList.add(new CityItem(   "PLAUEN              ",    "10569"));
               pcityList.add(new CityItem(   "PLYMOUTH            ",    "03827"));
               pcityList.add(new CityItem(   "PODGORICA/GOLUBOBCI ",    "13462"));
               pcityList.add(new CityItem(   "POITIERS            ",    "07335"));
               pcityList.add(new CityItem(   "POMMELSBRUNN-MITTEL.",    "P343"));
               pcityList.add(new CityItem(   "PONZA               ",    "16280"));
               pcityList.add(new CityItem(   "POPRAD/T.           ",    "11934"));
               pcityList.add(new CityItem(   "POREC               ",    "14301"));
               pcityList.add(new CityItem(   "PORTALEGRE          ",    "08571"));
               pcityList.add(new CityItem(   "PORTO               ",    "08545"));
               pcityList.add(new CityItem(   "POSEN               ",    "12330"));
               pcityList.add(new CityItem(   "POTSDAM             ",    "10379"));
               pcityList.add(new CityItem(   "PRACKENBACH         ",    "P472"));
               pcityList.add(new CityItem(   "PRAG FL.            ",    "11518"));
               pcityList.add(new CityItem(   "PRATICA DI MARE     ",    "16245"));
               pcityList.add(new CityItem(   "PRESTWICK/RNAS      ",    "03136"));
               pcityList.add(new CityItem(   "PRIBYSLAW           ",    "11659"));
               pcityList.add(new CityItem(   "PRIMDA              ",    "11423"));
               pcityList.add(new CityItem(   "PRISTINA            ",    "13481"));
               pcityList.add(new CityItem(   "PRIZREN             ",    "13477"));
               pcityList.add(new CityItem(   "PRIZZI              ",    "16434"));
               pcityList.add(new CityItem(   "PUERSCHLING         ",    "Z916"));
               pcityList.add(new CityItem(   "PULA                ",    "14307"));
               pcityList.add(new CityItem(   "PUTBUS              ",    "10093"));
               pcityList.add(new CityItem(   "QUEDLINBURG         ",    "N620"));
               pcityList.add(new CityItem(   "QUERFURT-LODERSL.   ",    "N748"));
               pcityList.add(new CityItem(   "QUICKBORN           ",    "10146"));
               pcityList.add(new CityItem(   "RAHDEN-VARL         ",    "H012"));
               pcityList.add(new CityItem(   "RAUSCHBERG          ",    "Z940"));
               pcityList.add(new CityItem(   "REGENSBURG          ",    "10776"));
               pcityList.add(new CityItem(   "REICHSHOF-ECKENHAGEN",    "H612"));
               pcityList.add(new CityItem(   "REIMLINGEN          ",    "P501"));
               pcityList.add(new CityItem(   "REIT IM WINKEL 2    ",    "P982"));
               pcityList.add(new CityItem(   "REITERALPE          ",    "Z943"));
               pcityList.add(new CityItem(   "RENNES              ",    "07130"));
               pcityList.add(new CityItem(   "RENNG. IHINGER-HOF  ",    "Q440"));
               pcityList.add(new CityItem(   "RESCHENPASS         ",    "16008"));
               pcityList.add(new CityItem(   "REYKJAVIK           ",    "04030"));
               pcityList.add(new CityItem(   "RHEINAU-MEMPRECHTSH.",    "Q404"));
               pcityList.add(new CityItem(   "RHEINFELDEN         ",    "Q909"));
               pcityList.add(new CityItem(   "RHEINSTETTEN        ",    "10731"));
               pcityList.add(new CityItem(   "RHODOS              ",    "16749"));
               pcityList.add(new CityItem(   "RIEDLINGEN          ",    "Q771"));
               pcityList.add(new CityItem(   "RIGA                ",    "26422"));
               pcityList.add(new CityItem(   "RIJEKA              ",    "14317"));
               pcityList.add(new CityItem(   "RISTNA              ",    "26115"));
               pcityList.add(new CityItem(   "ROCKENDORF          ",    "M765"));
               pcityList.add(new CityItem(   "ROELLBACH           ",    "P355"));
               pcityList.add(new CityItem(   "RONNEBY             ",    "02664"));
               pcityList.add(new CityItem(   "ROSENGARTEN-KLECKEN ",    "E273"));
               pcityList.add(new CityItem(   "ROSENHEIM           ",    "P877"));
               pcityList.add(new CityItem(   "ROTENBURG (WÜMME)   ",    "E355"));
               pcityList.add(new CityItem(   "ROTH                ",    "10765"));
               pcityList.add(new CityItem(   "ROTHENBURG OB DER TA",    "P305"));
               pcityList.add(new CityItem(   "ROTTERDAM           ",    "06344"));
               pcityList.add(new CityItem(   "ROTTWEIL            ",    "Q733"));
               pcityList.add(new CityItem(   "ROUEN               ",    "07037"));
               pcityList.add(new CityItem(   "RUNKEL-ENNERICH     ",    "L602"));
               pcityList.add(new CityItem(   "RUPPERTSECKEN       ",    "K762"));
               pcityList.add(new CityItem(   "RZESZOW-JASIONKA    ",    "12580"));
               pcityList.add(new CityItem(   "SAARBRUECKEN        ",    "10708"));
               pcityList.add(new CityItem(   "SAARBRUECKEN-BURBACH",    "J908"));
               pcityList.add(new CityItem(   "SACHSENHEIM         ",    "Q341"));
               pcityList.add(new CityItem(   "SAENTIS             ",    "06680"));
               pcityList.add(new CityItem(   "SALAMANCA/MATACAN   ",    "08202"));
               pcityList.add(new CityItem(   "SALDENBURG-ENTSCHENR",    "P586"));
               pcityList.add(new CityItem(   "SALZBURG FL.        ",    "11150"));
               pcityList.add(new CityItem(   "SAMARA              ",    "28807"));
               pcityList.add(new CityItem(   "SAMOS               ",    "16723"));
               pcityList.add(new CityItem(   "SAN SEBASTIAN/IGUEL.",    "08027"));
               pcityList.add(new CityItem(   "SANDBERG            ",    "P013"));
               pcityList.add(new CityItem(   "SANTA CRUZ DE TENE. ",    "60020"));
               pcityList.add(new CityItem(   "SANTA MARIA         ",    "08515"));
               pcityList.add(new CityItem(   "SANTANDER           ",    "08023"));
               pcityList.add(new CityItem(   "SARAJEVO-BEJELAVE   ",    "14654"));
               pcityList.add(new CityItem(   "SATENAS             ",    "02520"));
               pcityList.add(new CityItem(   "SCHAAFHEIM-SCHLIERB.",    "L894"));
               pcityList.add(new CityItem(   "SCHAUENBURG-ELGERSH.",    "10441"));
               pcityList.add(new CityItem(   "SCHIERKE            ",    "N601"));
               pcityList.add(new CityItem(   "SCHLEIZ             ",    "10564"));
               pcityList.add(new CityItem(   "SCHLESWIG           ",    "10035"));
               pcityList.add(new CityItem(   "SCHLESWIG-JAGEL     ",    "10037"));
               pcityList.add(new CityItem(   "SCHLÜCHTERN-HEROLZ  ",    "L678"));
               pcityList.add(new CityItem(   "SCHMIERITZ-WELTWITZ ",    "M772"));
               pcityList.add(new CityItem(   "SCHMUECKE           ",    "10552"));
               pcityList.add(new CityItem(   "SCHNEIFELFORSTHAUS  ",    "K210"));
               pcityList.add(new CityItem(   "SCHONUNGEN-MAINBERG ",    "P131"));
               pcityList.add(new CityItem(   "SCHORNDORF-KNOEBLING",    "P463"));
               pcityList.add(new CityItem(   "SCHOTTEN            ",    "L555"));
               pcityList.add(new CityItem(   "SCHROEDELSTEIN      ",    "Z928"));
               pcityList.add(new CityItem(   "SCHWANDORF          ",    "P366"));
               pcityList.add(new CityItem(   "SCHWARZBURG         ",    "M756"));
               pcityList.add(new CityItem(   "SCHWARZENBERG       ",    "Z909"));
               pcityList.add(new CityItem(   "SCHWB.-GMND/WEILER  ",    "Q378"));
               pcityList.add(new CityItem(   "SCHWERIN            ",    "10162"));
               pcityList.add(new CityItem(   "SEEHAUSEN           ",    "10261"));
               pcityList.add(new CityItem(   "SEESEN              ",    "E864"));
               pcityList.add(new CityItem(   "SELB/OBERFRANKEN    ",    "P098"));
               pcityList.add(new CityItem(   "SEVILLA/SAN PABLO   ",    "08391"));
               pcityList.add(new CityItem(   "SHANNON             ",    "03962"));
               pcityList.add(new CityItem(   "SHAWBURY            ",    "03414"));
               pcityList.add(new CityItem(   "SHOBDON             ",    "03520"));
               pcityList.add(new CityItem(   "SIAULIAI            ",    "26524"));
               pcityList.add(new CityItem(   "SIBIU               ",    "15260"));
               pcityList.add(new CityItem(   "SIEGSDORF-HOELL     ",    "P904"));
               pcityList.add(new CityItem(   "SIGMARINGEN-LAIZ    ",    "Q788"));
               pcityList.add(new CityItem(   "SIGMARSZELL-ZEISERTS",    "P887"));
               pcityList.add(new CityItem(   "SIMBACH/INN         ",    "P794"));
               pcityList.add(new CityItem(   "SIMMERN-WAHLBACH    ",    "K471"));
               pcityList.add(new CityItem(   "SINES (MONTES CHAOS)",    "08541"));
               pcityList.add(new CityItem(   "SINGEN              ",    "Q942"));
               pcityList.add(new CityItem(   "SINOP               ",    "17026"));
               pcityList.add(new CityItem(   "SIOFOK              ",    "12935"));
               pcityList.add(new CityItem(   "SION                ",    "06720"));
               pcityList.add(new CityItem(   "SIVAS               ",    "17090"));
               pcityList.add(new CityItem(   "SKOPJE              ",    "13586"));
               pcityList.add(new CityItem(   "SKYROS              ",    "16684"));
               pcityList.add(new CityItem(   "SLIAC               ",    "11903"));
               pcityList.add(new CityItem(   "SODANKYLA           ",    "02836"));
               pcityList.add(new CityItem(   "SOFIA               ",    "15614"));
               pcityList.add(new CityItem(   "SOHLAND/SPREE       ",    "O484"));
               pcityList.add(new CityItem(   "SOKOLAC             ",    "14658"));
               pcityList.add(new CityItem(   "SOLTAU              ",    "10235"));
               pcityList.add(new CityItem(   "SONTRA              ",    "L286"));
               pcityList.add(new CityItem(   "SOPRON              ",    "12805"));
               pcityList.add(new CityItem(   "SORTAVALA           ",    "22802"));
               pcityList.add(new CityItem(   "SOTSCHI             ",    "37171"));
               pcityList.add(new CityItem(   "SOUDA/AIRPORT       ",    "16746"));
               pcityList.add(new CityItem(   "SPITZINGSEE         ",    "Z932"));
               pcityList.add(new CityItem(   "SPLIT/MARJAN        ",    "14445"));
               pcityList.add(new CityItem(   "SPLIT/RESNIK        ",    "14444"));
               pcityList.add(new CityItem(   "ST. PETER ORDING    ",    "10028"));
               pcityList.add(new CityItem(   "ST. WOLFGANG        ",    "11357"));
               pcityList.add(new CityItem(   "ST.BRIEUC           ",    "07120"));
               pcityList.add(new CityItem(   "ST.HUBERT           ",    "06476"));
               pcityList.add(new CityItem(   "ST.MICHAEL/LUNGAU   ",    "11148"));
               pcityList.add(new CityItem(   "ST.PETERSBURG       ",    "26063"));
               pcityList.add(new CityItem(   "STAVANGER           ",    "01415"));
               pcityList.add(new CityItem(   "STEINAU,KR.CUXHAVEN ",    "E078"));
               pcityList.add(new CityItem(   "STEINHAGEN-NEGAST   ",    "B158"));
               pcityList.add(new CityItem(   "STETTIN             ",    "12205"));
               pcityList.add(new CityItem(   "STOCKHOLM           ",    "02464"));
               pcityList.add(new CityItem(   "STOETTEN            ",    "10836"));
               pcityList.add(new CityItem(   "STORNOWAY           ",    "03026"));
               pcityList.add(new CityItem(   "STRASSBURG          ",    "07190"));
               pcityList.add(new CityItem(   "STRAUBING           ",    "10788"));
               pcityList.add(new CityItem(   "STUTTGART-ECHT.     ",    "10738"));
               pcityList.add(new CityItem(   "STUTTGART-SCHN.     ",    "10739"));
               pcityList.add(new CityItem(   "STYLIS LAMIA        ",    "16675"));
               pcityList.add(new CityItem(   "SUWALKI             ",    "12195"));
               pcityList.add(new CityItem(   "SVALBARD            ",    "01008"));
               pcityList.add(new CityItem(   "SZEGED              ",    "12982"));
               pcityList.add(new CityItem(   "TALLIN              ",    "26038"));
               pcityList.add(new CityItem(   "TAMPERE             ",    "02944"));
               pcityList.add(new CityItem(   "TANN/RHOEN          ",    "L592"));
               pcityList.add(new CityItem(   "TARBES/OSSUN        ",    "07621"));
               pcityList.add(new CityItem(   "TARTU               ",    "26242"));
               pcityList.add(new CityItem(   "TARVISIO            ",    "16040"));
               pcityList.add(new CityItem(   "TEGELBERG           ",    "Z912"));
               pcityList.add(new CityItem(   "TEGELBERG-RUECKEN   ",    "Z910"));
               pcityList.add(new CityItem(   "TEGELBERGBAHN       ",    "Z911"));
               pcityList.add(new CityItem(   "TEGKWITZ            ",    "M488"));
               pcityList.add(new CityItem(   "TEKIRDAG            ",    "17056"));
               pcityList.add(new CityItem(   "TEL AVIV            ",    "40180"));
               pcityList.add(new CityItem(   "TETEROW             ",    "B556"));
               pcityList.add(new CityItem(   "TEUSCHNITZ          ",    "P071"));
               pcityList.add(new CityItem(   "THESSALONIKI        ",    "16622"));
               pcityList.add(new CityItem(   "THOLEY              ",    "10706"));
               pcityList.add(new CityItem(   "TIKSI               ",    "21824"));
               pcityList.add(new CityItem(   "TIMISOARA           ",    "15247"));
               pcityList.add(new CityItem(   "TIMRA/MIDLANDA      ",    "02366"));
               pcityList.add(new CityItem(   "TIRANA              ",    "13615"));
               pcityList.add(new CityItem(   "TIREE               ",    "03100"));
               pcityList.add(new CityItem(   "TIRSCHENREUTH-LODERM",    "P198"));
               pcityList.add(new CityItem(   "TIRSTRUP            ",    "06070"));
               pcityList.add(new CityItem(   "TOENISVORST         ",    "H522"));
               pcityList.add(new CityItem(   "TOLEDO BUENAVISTA   ",    "08272"));
               pcityList.add(new CityItem(   "TORUN               ",    "12250"));
               pcityList.add(new CityItem(   "TOTMA               ",    "27051"));
               pcityList.add(new CityItem(   "TOULOUSE            ",    "07630"));
               pcityList.add(new CityItem(   "TOURS               ",    "07240"));
               pcityList.add(new CityItem(   "TRABZON             ",    "17038"));
               pcityList.add(new CityItem(   "TRAPANI/BIRGI       ",    "16429"));
               pcityList.add(new CityItem(   "TREUEN              ",    "O868"));
               pcityList.add(new CityItem(   "TRIBSEES            ",    "B258"));
               pcityList.add(new CityItem(   "TRIER               ",    "10609"));
               pcityList.add(new CityItem(   "TRIER-ZEWEN         ",    "K611"));
               pcityList.add(new CityItem(   "TRIEST              ",    "16110"));
               pcityList.add(new CityItem(   "TRIPOLIS/INTL       ",    "16710"));
               pcityList.add(new CityItem(   "TROLLENHAGEN        ",    "10281"));
               pcityList.add(new CityItem(   "TROMSOE             ",    "01025"));
               pcityList.add(new CityItem(   "TRONDHEIM           ",    "01271"));
               pcityList.add(new CityItem(   "TROSTBERG           ",    "P881"));
               pcityList.add(new CityItem(   "TROYES              ",    "07168"));
               pcityList.add(new CityItem(   "TULA                ",    "27719"));
               pcityList.add(new CityItem(   "TULLINGE            ",    "02469"));
               pcityList.add(new CityItem(   "TUZLA               ",    "14557"));
               pcityList.add(new CityItem(   "TWENTHE             ",    "06290"));
               pcityList.add(new CityItem(   "TWISTETAL-MUEHLHAUS.",    "L121"));
               pcityList.add(new CityItem(   "UECKERMUENDE        ",    "10193"));
               pcityList.add(new CityItem(   "UELZEN              ",    "E475"));
               pcityList.add(new CityItem(   "UFS DEUTSCHE BUCHT  ",    "10007"));
               pcityList.add(new CityItem(   "UFS TW EMS          ",    "10004"));
               pcityList.add(new CityItem(   "ULM-MAEHRINGEN      ",    "10840"));
               pcityList.add(new CityItem(   "UMMENDORF           ",    "10356"));
               pcityList.add(new CityItem(   "USTI NAD ORLICI     ",    "11679"));
               pcityList.add(new CityItem(   "UTSIRA FYR          ",    "01403"));
               pcityList.add(new CityItem(   "VADUZ FL.           ",    "06990"));
               pcityList.add(new CityItem(   "VALENCIA            ",    "08284"));
               pcityList.add(new CityItem(   "VALENTIA            ",    "03953"));
               pcityList.add(new CityItem(   "VALJEVO             ",    "13269"));
               pcityList.add(new CityItem(   "VALKENBURG          ",    "06210"));
               pcityList.add(new CityItem(   "VALLADOLID          ",    "08141"));
               pcityList.add(new CityItem(   "VALLEY              ",    "03302"));
               pcityList.add(new CityItem(   "VAN                 ",    "17170"));
               pcityList.add(new CityItem(   "VANGSNES            ",    "01338"));
               pcityList.add(new CityItem(   "VARNA               ",    "15552"));
               pcityList.add(new CityItem(   "VEILSDORF           ",    "M927"));
               pcityList.add(new CityItem(   "VESTMANNAEYJAR      ",    "04048"));
               pcityList.add(new CityItem(   "VESZPREM            ",    "12830"));
               pcityList.add(new CityItem(   "VIGO/PEINADOR       ",    "08045"));
               pcityList.add(new CityItem(   "VIITASAARI          ",    "02915"));
               pcityList.add(new CityItem(   "VILA REAL           ",    "08567"));
               pcityList.add(new CityItem(   "VILLACH             ",    "11213"));
               pcityList.add(new CityItem(   "VILLINGEN-SCHWENNING",    "Q738"));
               pcityList.add(new CityItem(   "VILNIUS             ",    "26730"));
               pcityList.add(new CityItem(   "VISBY               ",    "02590"));
               pcityList.add(new CityItem(   "VITEBSK             ",    "26666"));
               pcityList.add(new CityItem(   "VOLGOGRAD           ",    "34560"));
               pcityList.add(new CityItem(   "VOLKEL              ",    "06375"));
               pcityList.add(new CityItem(   "VORONEZ             ",    "34123"));
               pcityList.add(new CityItem(   "VRANJE              ",    "13489"));
               pcityList.add(new CityItem(   "WADDINGTON          ",    "03377"));
               pcityList.add(new CityItem(   "WAGERSROTT          ",    "A191"));
               pcityList.add(new CityItem(   "WAGHAEUSEL-KIRRLACH ",    "Q104"));
               pcityList.add(new CityItem(   "WAHLSBURG-LIPPOLDSB.",    "L031"));
               pcityList.add(new CityItem(   "WAIBSTADT           ",    "10733"));
               pcityList.add(new CityItem(   "WALDEMS-REINBORN    ",    "L722"));
               pcityList.add(new CityItem(   "WALDMUENCHEN        ",    "10782"));
               pcityList.add(new CityItem(   "WALTERSHAUSEN       ",    "M520"));
               pcityList.add(new CityItem(   "WALTROP-ABDINGHOF   ",    "H443"));
               pcityList.add(new CityItem(   "WANGERLAND-HOOKSIEL ",    "E043"));
               pcityList.add(new CityItem(   "WARBURG             ",    "10435"));
               pcityList.add(new CityItem(   "WAREN               ",    "10268"));
               pcityList.add(new CityItem(   "WARNEMUENDE         ",    "10170"));
               pcityList.add(new CityItem(   "WARSCHAU            ",    "12375"));
               pcityList.add(new CityItem(   "WARTSTEINHUETTE     ",    "Z944"));
               pcityList.add(new CityItem(   "WARTSTEINKOPF       ",    "Z942"));
               pcityList.add(new CityItem(   "WASSERKUPPE         ",    "10544"));
               pcityList.add(new CityItem(   "WATTISHAM           ",    "03590"));
               pcityList.add(new CityItem(   "WEIDEN              ",    "10688"));
               pcityList.add(new CityItem(   "WEIDENBACH-WEIHERSCH",    "P319"));
               pcityList.add(new CityItem(   "WEIHENSTEPHAN       ",    "10863"));
               pcityList.add(new CityItem(   "WEILERSWIST-LOMMERSU",    "H932"));
               pcityList.add(new CityItem(   "WEIMAR-SCHOENDORF   ",    "M448"));
               pcityList.add(new CityItem(   "WEINBIET            ",    "10724"));
               pcityList.add(new CityItem(   "WEINGARTEN BEI RAVEN",    "Q879"));
               pcityList.add(new CityItem(   "WEISKIRCHEN/SAAR    ",    "J728"));
               pcityList.add(new CityItem(   "WEISSENBURG-EMETZH. ",    "10761"));
               pcityList.add(new CityItem(   "WENDELSTEIN-SOIN    ",    "Z934"));
               pcityList.add(new CityItem(   "WENDISCH EVERN      ",    "E298"));
               pcityList.add(new CityItem(   "WERL                ",    "10424"));
               pcityList.add(new CityItem(   "WERNIGERODE         ",    "10454"));
               pcityList.add(new CityItem(   "WEST FREUGH         ",    "03132"));
               pcityList.add(new CityItem(   "WESTERMARKELSDORF   ",    "10055"));
               pcityList.add(new CityItem(   "WICK                ",    "03075"));
               pcityList.add(new CityItem(   "WIELENBACH          ",    "P831"));
               pcityList.add(new CityItem(   "WIEN/HOHE WARTE     ",    "11035"));
               pcityList.add(new CityItem(   "WIESBADEN-AURINGEN  ",    "L821"));
               pcityList.add(new CityItem(   "WIESENBURG          ",    "10368"));
               pcityList.add(new CityItem(   "WITTENBERG          ",    "10474"));
               pcityList.add(new CityItem(   "WITTENBORN          ",    "A762"));
               pcityList.add(new CityItem(   "WITTERING           ",    "03462"));
               pcityList.add(new CityItem(   "WITTINGEN-VORHOP    ",    "E691"));
               pcityList.add(new CityItem(   "WITTMUNDHAVEN       ",    "10126"));
               pcityList.add(new CityItem(   "WITTSTOCK-ROTE MÜHLE",    "F143"));
               pcityList.add(new CityItem(   "WLADIKAVKAZ         ",    "37228"));
               pcityList.add(new CityItem(   "WOLFACH             ",    "Q622"));
               pcityList.add(new CityItem(   "WOLFSBURG (SUEDWEST)",    "E790"));
               pcityList.add(new CityItem(   "WORMS               ",    "K699"));
               pcityList.add(new CityItem(   "WORPSWEDE-HUETTENBUS",    "E254"));
               pcityList.add(new CityItem(   "WROCLAW II          ",    "12424"));
               pcityList.add(new CityItem(   "WUERZBURG           ",    "10655"));
               pcityList.add(new CityItem(   "WUNSIEDEL-SCHOENBRUN",    "10686"));
               pcityList.add(new CityItem(   "WUNSTORF            ",    "10334"));
               pcityList.add(new CityItem(   "WUSTERWITZ          ",    "F419"));
               pcityList.add(new CityItem(   "WUTOESCHINGEN-OFTER.",    "Q926"));
               pcityList.add(new CityItem(   "YEOVILTON           ",    "03853"));
               pcityList.add(new CityItem(   "ZAGREB/PLESO        ",    "14241"));
               pcityList.add(new CityItem(   "ZARAGOZA            ",    "08160"));
               pcityList.add(new CityItem(   "ZEHDENICK           ",    "F263"));
               pcityList.add(new CityItem(   "ZEITZ               ",    "N977"));
               pcityList.add(new CityItem(   "ZELL A.SEE          ",    "11144"));
               pcityList.add(new CityItem(   "ZENICA              ",    "14549"));
               pcityList.add(new CityItem(   "ZIELONA GORA        ",    "12400"));
               pcityList.add(new CityItem(   "ZINNWALD-G.         ",    "10582"));
               pcityList.add(new CityItem(   "ZLATIBOR            ",    "13367"));
               pcityList.add(new CityItem(   "ZONGULDAK           ",    "17022"));
               pcityList.add(new CityItem(   "ZUERICH             ",    "06670"));
               pcityList.add(new CityItem(   "ZUGSPITZE           ",    "10961"));
               pcityList.add(new CityItem(   "ZUGSPITZPLATT       ",    "Z914"));
               pcityList.add(new CityItem(   "ZWIESEL             ",    "10796"));
        return (pcityList);
    }
}
